# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"alacritty" = ""
"github" = ""
"picture-in-picture" = ""
"private browsing" = ""
"firefox" = ""
"chromium" = ""
"file manager" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"inkscape" = ""
"gnu image manipulation program" = ""
"emacs" = ""
"gthumb" = ""
"menu" = ""
"element" = ""
"calculator" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
"steam" = ""
"disk usage" = ""
"documents" = ""
".pdf" = ""
"*" = ""
